Chapter 07

# 鸡兔同笼-矩阵乘法
《线性代数》 | 鸢尾花书：数学不难

该代码使用线性代数的方法解决经典的“鸡兔同笼”问题。本质上，该问题可以被建模为一个 $2 \times 2$ 线性方程组，并通过矩阵求逆的方法进行求解。

---

### **1. 设定线性方程组**
设鸡的数量为 $x_1$，兔的数量为 $x_2$，我们得到如下两个方程：
$$
x_1 + x_2 = 35
$$
$$
2x_1 + 4x_2 = 94
$$
这个方程组可以用矩阵的形式表示为：
$$
A \mathbf{x} = \mathbf{b}
$$
其中：
$$
A = \begin{bmatrix} 1 & 1 \\ 2 & 4 \end{bmatrix}, \quad
\mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}, \quad
\mathbf{b} = \begin{bmatrix} 35 \\ 94 \end{bmatrix}
$$
矩阵 $A$ 是系数矩阵，向量 $\mathbf{x}$ 是未知数，向量 $\mathbf{b}$ 是右侧的常数列向量。

---

### **2. 计算矩阵 $A$ 的逆**
解方程 $\mathbf{x} = A^{-1} \mathbf{b}$ 需要先计算矩阵 $A$ 的逆：
$$
A^{-1} = \frac{1}{\det(A)} \operatorname{adj}(A)
$$
行列式 $\det(A)$ 计算如下：
$$
\det(A) = 1 \cdot 4 - 1 \cdot 2 = 2
$$
伴随矩阵（余子式矩阵的转置）：
$$
\operatorname{adj}(A) = \begin{bmatrix} 4 & -1 \\ -2 & 1 \end{bmatrix}
$$
因此，矩阵 $A$ 的逆为：
$$
A^{-1} = \frac{1}{2} \begin{bmatrix} 4 & -1 \\ -2 & 1 \end{bmatrix}
= \begin{bmatrix} 2 & -0.5 \\ -1 & 0.5 \end{bmatrix}
$$

---

### **3. 验证逆矩阵**
代码通过计算 $A^{-1} A$ 和 $A A^{-1}$ 来验证矩阵 $A$ 的逆是否正确：
$$
A^{-1} A = \begin{bmatrix} 2 & -0.5 \\ -1 & 0.5 \end{bmatrix}
\begin{bmatrix} 1 & 1 \\ 2 & 4 \end{bmatrix} = 
\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
$$
$$
A A^{-1} = \begin{bmatrix} 1 & 1 \\ 2 & 4 \end{bmatrix}
\begin{bmatrix} 2 & -0.5 \\ -1 & 0.5 \end{bmatrix} = 
\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
$$
这表明 $A^{-1}$ 计算正确。

---

### **4. 计算最终解**
最终，使用 $A^{-1} b$ 计算未知数 $\mathbf{x}$：
$$
\mathbf{x} = A^{-1} \mathbf{b} = 
\begin{bmatrix} 2 & -0.5 \\ -1 & 0.5 \end{bmatrix}
\begin{bmatrix} 35 \\ 94 \end{bmatrix}
$$
进行矩阵乘法：
$$
x_1 = 2 \times 35 + (-0.5) \times 94 = 70 - 47 = 23
$$
$$
x_2 = -1 \times 35 + 0.5 \times 94 = -35 + 47 = 12
$$
因此，鸡的数量是 **23**，兔的数量是 **12**。

---

### **总结**
本代码基于矩阵运算求解 $2 \times 2$ 线性方程组，核心步骤如下：
1. 设定矩阵方程 $A \mathbf{x} = \mathbf{b}$。
2. 计算 $A$ 的逆矩阵 $A^{-1}$。
3. 验证 $A^{-1}$ 是否正确。
4. 计算 $A^{-1} b$ 得到未知数的值，即 **鸡 23 只，兔 12 只**。

这个方法是利用矩阵求逆来解线性方程组的一种常见方式，但在高维情况下，通常采用高斯消元法或 LU 分解等更高效的数值方法。

## 初始化

In [1]:
import numpy as np

## 鸡兔同笼系数矩阵

In [3]:
A = np.array([[1, 1], 
              [2, 4]])
# a_1, chicken 
# a_2, rabbit

## 常数列向量

In [5]:
b = np.array([[35],
              [94]])

## 矩阵A的逆

In [9]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 2. , -0.5],
       [-1. ,  0.5]])

In [11]:
# 验证
A_inv @ A

array([[1., 0.],
       [0., 1.]])

In [13]:
A @ A_inv

array([[1., 0.],
       [0., 1.]])

## 求解

In [15]:
A_inv @ b

array([[23.],
       [12.]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  