Chapter 09

# 施密特正交化，自定义函数
《线性代数》 | 鸢尾花书：数学不难

这段代码通过 Gram-Schmidt 过程对一个实数矩阵 $A$ 进行正交化，完成 **QR 分解**：将矩阵 $A$ 分解为正交矩阵 $Q$ 和上三角矩阵 $R$，满足 $A = QR$。这一分解在数值分析、最小二乘法、特征值计算等领域具有重要意义。

---

首先导入 NumPy，并定义一个函数 `gram_schmidt_qr(A)`，用于执行格拉姆-施密特正交化过程。这个函数适用于任意形状为 $m \times n$ 的实矩阵 $A$，其中 $m \geq n$ 且 $A$ 的列向量线性无关。

整个正交化过程的核心思想是将原始的 $A$ 按列处理，将每个列向量 $\boldsymbol{a}_i$ 转换为单位正交向量 $\boldsymbol{q}_i$，并用这些 $\boldsymbol{q}_i$ 构成矩阵 $Q$。每列向量的处理分为两个步骤：**去除投影分量（正交化）** 和 **单位化**。

---

在第 $i$ 步中，我们处理矩阵 $A$ 的第 $i$ 列向量 $\boldsymbol{a}_i$：

1. 先依次从 $\boldsymbol{a}_i$ 中减去它在先前所有 $\boldsymbol{q}_j\ (j < i)$ 上的投影：
   $$
   \boldsymbol{a}_i' = \boldsymbol{a}_i - \sum_{j=0}^{i-1} R_{ji} \boldsymbol{q}_j,\quad\text{其中}\ R_{ji} = \boldsymbol{q}_j^\top \boldsymbol{a}_i
   $$
   这一过程确保了 $\boldsymbol{a}_i'$ 与所有之前的 $\boldsymbol{q}_j$ 都正交。

2. 然后将这个结果单位化：
   $$
   \boldsymbol{q}_i = \frac{\boldsymbol{a}_i'}{\|\boldsymbol{a}_i'\|},\quad R_{ii} = \|\boldsymbol{a}_i'\|
   $$
   从而得到新的单位正交向量 $\boldsymbol{q}_i$。

最终得到的矩阵 $Q = [\boldsymbol{q}_1\ \boldsymbol{q}_2\ \dots\ \boldsymbol{q}_n]$ 满足列向量两两正交且范数为 1，即：

$$
Q^\top Q = I_n
$$

而矩阵 $R$ 是上三角矩阵，记录了每个原始向量在正交基上的投影系数。这样就得到了：

$$
A = QR
$$

---

在本例中，构造了如下 $3 \times 3$ 的矩阵 $A$：

$$
A = \begin{bmatrix}
2 & 2 & 0 \\
2 & 0 & 2 \\
0 & 2 & 2
\end{bmatrix}
$$

调用函数 `gram_schmidt_qr(A)` 后，返回的 $Q$ 为列正交矩阵，$R$ 为上三角矩阵。用 `np.round(Q.T @ Q, 6)` 验证 $Q^\top Q$ 的结果是否为单位矩阵，确保向量组是单位正交组，说明正交化过程成功。

---

这套流程不仅实现了 QR 分解，还保留了每一步中的投影和归一化结构，有助于理解 QR 的几何意义：每一列是“去掉前面分量并重新归一化”后的新基向量。这个过程也为最小二乘法提供了核心工具。

## 初始化

In [3]:
import numpy as np

## 自定义函数

In [13]:
def gram_schmidt_qr(A):
    """
    对实数矩阵 A 执行格拉姆-施密特正交化，返回 Q, R，使 A = Q @ R
    Q 为单位正交列向量矩阵，R 为上三角矩阵

    参数：
    A : np.ndarray，形状 (m, n)，m ≥ n

    返回：
    Q : np.ndarray，形状 (m, n)，单位正交列向量
    R : np.ndarray，形状 (n, n)，上三角矩阵
    """
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for i in range(n):
        ai = A[:, i].reshape(-1, 1)
        for j in range(i):
            qj = Q[:, j].reshape(-1, 1)
            R[j, i] = (qj.T @ ai).item()
            ai = ai - R[j, i] * qj      # 执行正交投影剔除

        norm = np.linalg.norm(ai)
        if norm < 1e-10:
            raise ValueError(f"第 {i+1} 列向量线性相关，无法正交化")

        Q[:, i] = (ai / norm).flatten()
        R[i, i] = norm                # 对角线元素

    return Q, R


## 创建数据

In [7]:
A = np.array([
    [2, 2, 0],
    [2, 0, 2],
    [0, 2, 2]])

## 调用函数

In [15]:
Q,R = gram_schmidt_qr(A)

In [19]:
Q

array([[ 0.70710678,  0.40824829, -0.57735027],
       [ 0.70710678, -0.40824829,  0.57735027],
       [ 0.        ,  0.81649658,  0.57735027]])

In [21]:
R

array([[2.82842712, 1.41421356, 1.41421356],
       [0.        , 2.44948974, 0.81649658],
       [0.        , 0.        , 2.30940108]])

In [24]:
# 验证正交性
np.round(Q.T @ Q, 6)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  