Chapter 03

# Python自定义函数计算矩阵乘法，列向量线性组合视角
《线性代数》 | 鸢尾花书：数学不难

这段代码的核心目的是**用列向量的线性组合来重新诠释矩阵乘法的本质**，并实现了两个矩阵乘积的计算过程：$AB$ 和 $BA$。我们从数学角度来解释整个过程。

---

### 一、矩阵乘法的列向量解释

我们知道，矩阵乘法 $C = AB$（设 $A$ 为 $m \times p$ 矩阵，$B$ 为 $p \times n$ 矩阵）可以从不同的角度理解：
- 按 **行与列点积** 来看，$C_{ij}$ 是 $A$ 第 $i$ 行与 $B$ 第 $j$ 列的点积；
- 本段代码采用的是另一种等价的思维方式：**列向量线性组合**。

具体来说，我们将 $B$ 的每一列 $\mathbf{b}_j$（$j = 1, \dots, n$）作为一组**线性组合系数**，将其作用在矩阵 $A$ 的列向量上：
$$
C[:, j] = A \cdot \mathbf{b}_j = \sum_{k=1}^p b_{kj} \cdot A[:, k]
$$

也就是说，第 $j$ 列的结果是由 $A$ 的列向量 $\{A[:, 1], \dots, A[:, p]\}$ 加权相加得到的。

---

### 二、函数解释：`col_LC`

函数 `col_LC(A, coefficients)` 的数学含义是：

> 给定一个矩阵 $A \in \mathbb{R}^{m \times p}$ 和一个系数向量 $\mathbf{c} \in \mathbb{R}^p$，输出向量
$$
\mathbf{v} = \sum_{k=1}^p c_k \cdot \mathbf{a}_k
$$
其中 $\mathbf{a}_k = A[:, k]$ 是 $A$ 的第 $k$ 列。

这是线性代数中最基础的线性组合的定义。

---

### 三、函数解释：`matrix_multiplication_col_LC`

这个函数的目标是用线性组合的方法实现矩阵乘法 $C = AB$，其中：
- $A \in \mathbb{R}^{m \times p}$
- $B \in \mathbb{R}^{p \times n}$
- 结果 $C \in \mathbb{R}^{m \times n}$

具体过程如下：

对于 $j = 1$ 到 $n$：
- 取出 $B$ 的第 $j$ 列 $\mathbf{b}_j$
- 用 $A$ 的列向量加权组合：
$$
C[:, j] = A \cdot \mathbf{b}_j = \sum_{k=1}^p b_{kj} \cdot A[:, k]
$$

这个思想把矩阵乘法分解为 **多个列向量组合问题**。

---

### 四、矩阵示例：$A$, $B = A^T$

代码中具体的矩阵如下：

$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix} \in \mathbb{R}^{2 \times 3}
$$

则它的转置为：

$$
B = A^T = \begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix} \in \mathbb{R}^{3 \times 2}
$$

---

### 五、计算 $AB$

使用 `matrix_multiplication_col_LC(A, B)`，相当于计算：

$$
C = AB = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
= 
\begin{bmatrix}
14 & 32 \\
32 & 77
\end{bmatrix}
$$

计算过程如下：

- 第1列：$A$ 的列向量组合，权重为 $[1, 2, 3]$
  $$
  A[:,1]*1 + A[:,2]*2 + A[:,3]*3 =
  \begin{bmatrix} 1 \\ 4 \end{bmatrix}*1 +
  \begin{bmatrix} 2 \\ 5 \end{bmatrix}*2 +
  \begin{bmatrix} 3 \\ 6 \end{bmatrix}*3 =
  \begin{bmatrix} 14 \\ 32 \end{bmatrix}
  $$

- 第2列：权重为 $[4, 5, 6]$
  $$
  A[:,1]*4 + A[:,2]*5 + A[:,3]*6 =
  \begin{bmatrix} 32 \\ 77 \end{bmatrix}
  $$

---

### 六、计算 $BA$

再看另一个方向的乘法 `matrix_multiplication_col_LC(B, A)` 相当于计算：

$$
BA = \begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
=
\begin{bmatrix}
17 & 22 & 27 \\
22 & 29 & 36 \\
27 & 36 & 45
\end{bmatrix}
$$

计算原理同样是：把 $A$ 的列作为系数，作用于 $B$ 的列向量。

---

### 七、总结

这段代码把经典的矩阵乘法公式
$$
C = AB \quad\text{其中 } C_{ij} = \sum_{k=1}^p A_{ik} B_{kj}
$$
重新表达为**列向量线性组合的方式**：
$$
C[:, j] = \sum_{k=1}^p B_{kj} \cdot A[:, k]
$$

这种方式不仅加深对矩阵乘法本质的理解，还特别适合教学和理论推导（如在表示线性变换、特征空间、张量表示时）。

如需，我可以再进一步推导其与线性变换的几何意义或在机器学习中应用的联系。是否继续？

## 初始化

In [4]:
import numpy as np

## 定义列向量线性组合函数

In [6]:
def col_LC(A, coefficients):

    m, p = A.shape
    col_LC_result = np.zeros(m)  # 初始化组合结果
    
    for k in range(p):
        col_LC_result += coefficients[k] * A[:, k]  
        # A (左侧) 每列乘系数并相加
    return col_LC_result

## 定义矩阵乘法函数，列向量组合

In [8]:
def matrix_multiplication_col_LC(A, B):
    # 获取矩阵 A 和 B 的形状
    m, p_A = A.shape
    p_B, n = B.shape

    # 检测矩阵形状是否符合矩阵乘法规则
    if p_A != p_B:
        raise ValueError('Dimensions do not match')

    # 初始化结果矩阵 C，形状 (m, n)，初始值设为 0
    C = np.zeros((m, n))

    for j in range(n):
        coeffs = B[:, j]             
        # 取出 B 的第 j 列，作为线性组合的系数
        C[:, j] = col_LC(A, coeffs)  
        # 计算 A 的列的线性组合
    
    return C

## 矩阵乘法

In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

## 矩阵乘法

In [13]:
matrix_multiplication_col_LC(A, B)

array([[14., 32.],
       [32., 77.]])

In [14]:
A @ B

array([[14, 32],
       [32, 77]])

In [15]:
matrix_multiplication_col_LC(B, A)

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])

In [ ]:
B @ A

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  