Chapter 02

# 不同形状的矩阵转置
《线性代数》 | 鸢尾花书：数学不难

这段代码主要研究不同类型的向量和矩阵，并分析它们的转置性质。代码从基本的行向量、列向量到更复杂的矩阵（细高矩阵、扁平矩阵、方阵、对称矩阵）逐步展开，并使用 `.T` 进行转置操作。下面是详细的数学分析：

---

### **1. 行向量（1D 数组）**
代码首先定义了一个一维 NumPy 数组：
$$
\text{row\_vector\_1d} = \begin{bmatrix} 1 & 2 & 3 & 4 \end{bmatrix}
$$
在 NumPy 中，这是一个 **1D 数组**，其形状为 $(4,)$。尝试对其执行 `.T` 操作不会改变形状，因为 NumPy 认为它是一个 **扁平数组**，而不是严格意义上的矩阵。因此：
$$
\text{row\_vector\_1d}^T = \text{row\_vector\_1d}
$$
这表明对于 **1D 数组而言，转置没有作用**。

---

### **2. 行向量（2D 数组）**
为了保证转置的正确性，我们使用二维数组：
$$
\text{row\_vector\_2d} = \begin{bmatrix} 1 & 2 & 3 & 4 \end{bmatrix}
$$
其形状为 $(1,4)$。此时，对其执行 `.T` 转置操作，会变为列向量：
$$
\text{row\_vector\_2d}^T =
\begin{bmatrix} 1 \\ 2 \\ 3 \\ 4 \end{bmatrix}
$$
转置后的形状变为 $(4,1)$，即一个 **列向量**。

---

### **3. 列向量（2D 数组）**
定义一个 **列向量**：
$$
\text{col\_vector} =
\begin{bmatrix} 1 \\ 2 \\ 3 \\ 4 \end{bmatrix}
$$
其形状为 $(4,1)$。执行 `.T` 之后：
$$
\text{col\_vector}^T =
\begin{bmatrix} 1 & 2 & 3 & 4 \end{bmatrix}
$$
转置后的形状变为 $(1,4)$，即变为一个 **行向量**。

---

### **4. 细高矩阵（Tall Matrix）**
代码定义了一个 **细高矩阵**，即行数大于列数的矩阵：
$$
\text{tall\_matrix} =
\begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}
$$
形状为 $(3,2)$。执行 `.T` 转置后：
$$
\text{tall\_matrix}^T =
\begin{bmatrix} 1 & 3 & 5 \\ 2 & 4 & 6 \end{bmatrix}
$$
转置后的形状变为 $(2,3)$，行数和列数发生互换。

---

### **5. 扁平矩阵（Wide Matrix）**
定义一个 **扁平矩阵**，即列数大于行数：
$$
\text{wide\_matrix} =
\begin{bmatrix} 1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \end{bmatrix}
$$
形状为 $(2,4)$。执行 `.T` 转置后：
$$
\text{wide\_matrix}^T =
\begin{bmatrix} 1 & 5 \\ 2 & 6 \\ 3 & 7 \\ 4 & 8 \end{bmatrix}
$$
转置后的形状变为 $(4,2)$，行列互换。

---

### **6. 方阵（Square Matrix）**
方阵是行数等于列数的矩阵：
$$
\text{square\_matrix} =
\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}
$$
形状为 $(3,3)$。执行 `.T` 转置后：
$$
\text{square\_matrix}^T =
\begin{bmatrix} 1 & 4 & 7 \\ 2 & 5 & 8 \\ 3 & 6 & 9 \end{bmatrix}
$$
转置仍然是一个 $(3,3)$ 的方阵，但主对角线之外的元素发生了交换。

---

### **7. 对称矩阵（Symmetric Matrix）**
定义一个 **对称矩阵**：
$$
\text{symmetric\_matrix} =
\begin{bmatrix} 1 & 2 & 3 \\ 2 & 4 & 5 \\ 3 & 5 & 6 \end{bmatrix}
$$
它的转置为：
$$
\text{symmetric\_matrix}^T =
\begin{bmatrix} 1 & 2 & 3 \\ 2 & 4 & 5 \\ 3 & 5 & 6 \end{bmatrix}
$$
由于 $A^T = A$，所以该矩阵是**对称矩阵**。

---

### **总结**
1. **1D 数组（行向量）** 在 NumPy 中不能正确转置，仍然是 1D 数组。
2. **2D 行向量** 可以正确转置，变为列向量。
3. **2D 列向量** 也可以正确转置，变为行向量。
4. **矩阵的转置** 是将行和列互换：
   - 细高矩阵的转置变为扁平矩阵。
   - 扁平矩阵的转置变为细高矩阵。
   - 方阵的转置仍然是方阵，但元素交换。
5. **对称矩阵** 满足 $A^T = A$，因此转置后不变。

这些操作是线性代数和数据科学中的基础概念，广泛应用于机器学习、信号处理和图像分析中。

## 初始化

In [4]:
import numpy as np

## 行向量（1D 数组）

In [6]:
row_vector_1d = np.array([1, 2, 3, 4])  # 一维数组（行向量）
row_vector_1d

array([1, 2, 3, 4])

In [7]:
row_vector_1d.T

array([1, 2, 3, 4])

## 行向量（2D 数组）

In [9]:
row_vector_2d = np.array([[1, 2, 3, 4]])  # 2D 行向量
row_vector_2d

array([[1, 2, 3, 4]])

In [10]:
row_vector_2d.T

array([[1],
       [2],
       [3],
       [4]])

In [11]:
## 列向量（2D 数组）

In [12]:
col_vector = np.array([[1], [2], [3], [4]]) 

In [13]:
col_vector

array([[1],
       [2],
       [3],
       [4]])

In [14]:
col_vector.T

array([[1, 2, 3, 4]])

## 细高矩阵

In [16]:
tall_matrix = np.array([[1, 2], 
                        [3, 4], 
                        [5, 6]])
tall_matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
tall_matrix.T

array([[1, 3, 5],
       [2, 4, 6]])

In [18]:
## 扁平矩阵（2x4）
wide_matrix = np.array([[1, 2, 3, 4], 
                        [5, 6, 7, 8]])
wide_matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
wide_matrix.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## 方阵（3x3）

In [21]:
square_matrix = np.array([[1, 2, 3], 
                          [4, 5, 6], 
                          [7, 8, 9]])
square_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
square_matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 对称矩阵（3x3）

In [24]:
symmetric_matrix = np.array([[1, 2, 3], 
                             [2, 4, 5], 
                             [3, 5, 6]])

In [25]:
symmetric_matrix

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 6]])

In [26]:
symmetric_matrix.T

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 6]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  