Chapter 06

# 秩
《线性代数》 | 鸢尾花书：数学不难

这段代码的核心目的是利用线性代数的方法，分析不同矩阵的秩（rank），即它们的列向量是否线性相关或独立。代码主要通过构造不同的列向量矩阵，然后计算其秩，来验证线性代数中的基本概念。

---

### **初始化标准基向量**
代码首先定义了标准基向量 $e_1, e_2, e_3$，这些向量是 $\mathbb{R}^3$ 空间中的单位列向量：
$$
e_1 = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}, \quad
e_2 = \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}, \quad
e_3 = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}
$$
这些向量构成了 $\mathbb{R}^3$ 的标准正交基。

---

### **计算矩阵 $A$ 的秩**
矩阵 $A$ 由 $e_1, e_2, e_3$ 作为列向量构成：
$$
A = \begin{bmatrix} e_1 & e_2 & e_3 \end{bmatrix} =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$
这是 $3 \times 3$ 的单位矩阵（即标准基向量组成的矩阵），它的列向量是线性无关的，因此矩阵 $A$ 的秩为：
$$
\text{rank}(A) = 3
$$

---

### **计算矩阵 $B$ 的秩**
矩阵 $B$ 由 $e_1, e_2, e_1 + e_2$ 作为列向量构成：
$$
B = \begin{bmatrix} e_1 & e_2 & e_1 + e_2 \end{bmatrix} =
\begin{bmatrix}
1 & 0 & 1+0 \\
0 & 1 & 0+1 \\
0 & 0 & 0+0
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 & 1 \\
0 & 1 & 1 \\
0 & 0 & 0
\end{bmatrix}
$$
这个矩阵的第三列是前两列的线性组合：
$$
e_1 + e_2 = 1 \cdot e_1 + 1 \cdot e_2
$$
因此，矩阵 $B$ 的秩为 $2$，即：
$$
\text{rank}(B) = 2
$$
因为它只有两个线性无关的列向量。

---

### **计算矩阵 $C$ 的秩**
矩阵 $C$ 由 $e_1, e_2$ 作为列向量构成：
$$
C = \begin{bmatrix} e_1 & e_2 \end{bmatrix} =
\begin{bmatrix}
1 & 0 \\
0 & 1 \\
0 & 0
\end{bmatrix}
$$
该矩阵只有两列，它们是线性无关的，因此秩为：
$$
\text{rank}(C) = 2
$$

---

### **计算矩阵 $D$ 的秩**
矩阵 $D$ 由 $e_1, -e_1, \frac{1}{2} e_1$ 作为列向量构成：
$$
D = \begin{bmatrix} e_1 & -e_1 & \frac{1}{2} e_1 \end{bmatrix} =
\begin{bmatrix}
1 & -1 & \frac{1}{2} \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}
$$
由于第二、第三行全为零，该矩阵的秩仅由第一行决定。观察其列向量：
- 第二列是第一列的 $-1$ 倍。
- 第三列是第一列的 $\frac{1}{2}$ 倍。

因此，矩阵 $D$ 只有一个线性无关的列向量，它的秩为：
$$
\text{rank}(D) = 1
$$

---

### **总结**
- $A$ 是单位矩阵，列向量线性无关，$\text{rank}(A) = 3$。
- $B$ 中的第三列是前两列的线性组合，$\text{rank}(B) = 2$。
- $C$ 只有两个独立的列向量，$\text{rank}(C) = 2$。
- $D$ 的三列是线性相关的，秩降为 $1$，即 $\text{rank}(D) = 1$。

通过这四个案例，我们验证了线性代数中的基本秩概念，包括：
1. 单位矩阵的秩等于维数。
2. 向量线性相关时会导致秩降低。
3. 线性组合不会增加秩。

这一分析在高维空间、特征分析、降维（如 PCA）等问题中有广泛应用。

## 初始化

In [2]:
import numpy as np

## 定义列向量

In [4]:
e_1 = np.array([[1],
                [0],
                [0]])

e_2 = np.array([[0],
                [1],
                [0]])

e_3 = np.array([[0],
                [0],
                [1]])

## 计算秩

In [8]:
A = np.column_stack([e_1, e_2, e_3])
A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [10]:
np.linalg.matrix_rank(A)

3

In [12]:
B = np.column_stack([e_1, e_2, e_1 + e_2])
B

array([[1, 0, 1],
       [0, 1, 1],
       [0, 0, 0]])

In [14]:
np.linalg.matrix_rank(B)

2

In [16]:
C = np.column_stack([e_1, e_2])
C

array([[1, 0],
       [0, 1],
       [0, 0]])

In [18]:
np.linalg.matrix_rank(C)

2

In [22]:
D = np.column_stack([e_1, -e_1, e_1/2])
D

array([[ 1. , -1. ,  0.5],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ]])

In [24]:
np.linalg.matrix_rank(D)

1

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  