Chapter 02

# 自定义函数计算矩阵乘法
《线性代数》 | 鸢尾花书：数学不难

这段代码的主要任务是从数学角度实现**矩阵乘法**（Matrix Multiplication）的过程，并验证其在不同矩阵顺序下的结果。以下是对代码的详细数学解释：

---

### 1. **矩阵乘法的基本原理**

设有两个矩阵 $A \in \mathbb{R}^{m \times p}$ 和 $B \in \mathbb{R}^{p \times n}$，它们的乘积定义为一个新的矩阵 $C \in \mathbb{R}^{m \times n}$，满足：

$$
C_{ij} = \sum_{k=1}^{p} A_{ik} \cdot B_{kj}, \quad \text{其中 } 1 \leq i \leq m,\ 1 \leq j \leq n
$$

这意味着，$C$ 的第 $i$ 行第 $j$ 列的元素是 $A$ 的第 $i$ 行和 $B$ 的第 $j$ 列的**点积**。

---

### 2. **代码实现的数学对应**

定义的函数 `matrix_multiplication(A, B)` 实际上就是实现上述公式的计算方式：

- 首先获取矩阵 $A$ 和 $B$ 的形状分别为 $(m, p_A)$ 和 $(p_B, n)$。
- 然后检查是否满足矩阵乘法的条件，即 $p_A = p_B$，对应数学上的 $A \in \mathbb{R}^{m \times p}$ 和 $B \in \mathbb{R}^{p \times n}$。
- 接着创建零矩阵 $C \in \mathbb{R}^{m \times n}$。
- 使用三重循环实现：

$$
\text{for } i = 0 \text{ to } m-1:\\
\quad \text{for } j = 0 \text{ to } n-1:\\
\quad\quad \text{for } k = 0 \text{ to } p-1:\\
\quad\quad\quad C[i,j] \mathrel{+}= A[i,k] \cdot B[k,j]
$$

该循环逐元素计算并累加 $C_{ij}$ 的值，和上述数学定义完全一致。

---

### 3. **具体矩阵的构造与运算**

矩阵 $A$ 被定义为：

$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix} \in \mathbb{R}^{2 \times 3}
$$

然后取其转置得到：

$$
B = A^\top = \begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix} \in \mathbb{R}^{3 \times 2}
$$

再进行两次矩阵乘法：

#### (1) $A \cdot B$

$$
A \cdot B = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
\cdot
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
= \begin{bmatrix}
1\cdot1 + 2\cdot2 + 3\cdot3 & 1\cdot4 + 2\cdot5 + 3\cdot6 \\
4\cdot1 + 5\cdot2 + 6\cdot3 & 4\cdot4 + 5\cdot5 + 6\cdot6
\end{bmatrix}
= \begin{bmatrix}
14 & 32 \\
32 & 77
\end{bmatrix}
$$

#### (2) $B \cdot A$

$$
B \cdot A = \begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
\cdot
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
= \begin{bmatrix}
1\cdot1 + 4\cdot4 & 1\cdot2 + 4\cdot5 & 1\cdot3 + 4\cdot6 \\
2\cdot1 + 5\cdot4 & 2\cdot2 + 5\cdot5 & 2\cdot3 + 5\cdot6 \\
3\cdot1 + 6\cdot4 & 3\cdot2 + 6\cdot5 & 3\cdot3 + 6\cdot6
\end{bmatrix}
= \begin{bmatrix}
17 & 22 & 27 \\
22 & 29 & 36 \\
27 & 36 & 45
\end{bmatrix}
$$

---

### 4. **总结**

本代码实现的是基础线性代数中最核心的运算之一：**矩阵乘法**，其数学本质是将一个矩阵的行向量与另一个矩阵的列向量进行点积。由于使用的是纯 Python 的循环方式（而不是 NumPy 的矢量化计算），这也帮助我们直观理解矩阵乘法的底层运算逻辑，尤其对学习者理解以下公式至关重要：

$$
C_{ij} = \sum_{k=1}^{p} A_{ik} \cdot B_{kj}
$$

这个公式是整个函数 `matrix_multiplication` 的核心。

## 初始化

In [2]:
import numpy as np

## 自定义函数

In [4]:
def matrix_multiplication(A, B):

    # 获取矩阵 A 和 B 的形状
    m, p_A = A.shape
    p_B, n = B.shape

    # 检测矩阵形状是否符合矩阵乘法规则
    if p_A != p_B:
        raise ValueError('Dimensions do not match')

    # 初始化结果矩阵 C，形状 (m, n)，初始值设为 0
    C = np.zeros((m, n))

    # 进行矩阵乘法计算，使用三层 for 循环
    for i in range(m):        # 遍历 A 的行
        for j in range(n):    # 遍历 B 的列
            for k in range(p_A):  # 遍历 A 的列 / B 的行
                C[i, j] += A[i, k] * B[k, j]  # 逐元素累加

    return C

## 定义矩阵

In [15]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

## 矩阵乘法

In [20]:
matrix_multiplication(A, B)

array([[14., 32.],
       [32., 77.]])

In [22]:
matrix_multiplication(B, A)

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  