Chapter 01

# 向量正交分解
《线性代数》 | 鸢尾花书：数学不难

这段代码的数学核心思想是：**将一个二维向量 $\mathbf{a}$ 沿任意旋转角 $\theta$ 所定义的正交基向量进行正交分解（orthogonal decomposition）**，即把 $\mathbf{a}$ 拆分成在这组正交基下的两个分量，并验证它们之和仍等于原始向量。

---

### 数学背景和目标

已知一个二维向量 $\mathbf{a} = \begin{bmatrix} 3 \\ 4 \end{bmatrix}$，我们希望将它分解为两个正交方向上的分量：

- 方向一：与单位向量 $\mathbf{v}_1$ 方向相同，定义为  
  $$\mathbf{v}_1 = \begin{bmatrix} \cos\theta \\ \sin\theta \end{bmatrix}$$
- 方向二：与单位向量 $\mathbf{v}_2$ 方向相同，垂直于 $\mathbf{v}_1$，定义为  
  $$\mathbf{v}_2 = \begin{bmatrix} -\sin\theta \\ \cos\theta \end{bmatrix}$$

$\mathbf{v}_1$ 和 $\mathbf{v}_2$ 构成一个二维空间中的**标准正交基底（orthonormal basis）**。

我们要做的是将 $\mathbf{a}$ 写成两个正交向量的和，即：
$$
\mathbf{a} = \mathbf{a}_{\mathbf{v}_1} + \mathbf{a}_{\mathbf{v}_2}
$$
其中：

- $\mathbf{a}_{\mathbf{v}_1}$ 是 $\mathbf{a}$ 在 $\mathbf{v}_1$ 方向上的投影；
- $\mathbf{a}_{\mathbf{v}_2}$ 是 $\mathbf{a}$ 在 $\mathbf{v}_2$ 方向上的投影。

---

### 投影计算方法

对于任意向量 $\mathbf{a}$ 和单位向量 $\mathbf{v}$，其在 $\mathbf{v}$ 方向上的投影公式为：

- **标量投影（投影坐标）：**  
  $$
  \text{scalar\_proj}_{\mathbf{v}}(\mathbf{a}) = \mathbf{a} \cdot \mathbf{v}
  $$
- **向量投影：**  
  $$
  \text{proj}_{\mathbf{v}}(\mathbf{a}) = (\mathbf{a} \cdot \mathbf{v}) \cdot \mathbf{v}
  $$

因此我们得到两个向量投影：

$$
\mathbf{a}_{\mathbf{v}_1} = (\mathbf{a} \cdot \mathbf{v}_1) \cdot \mathbf{v}_1 \\
\mathbf{a}_{\mathbf{v}_2} = (\mathbf{a} \cdot \mathbf{v}_2) \cdot \mathbf{v}_2
$$

最终验证：
$$
\mathbf{a}_{\mathbf{v}_1} + \mathbf{a}_{\mathbf{v}_2} = \mathbf{a}
$$

---

### 数值代入说明

代码中 $\theta = 30^\circ$，被转化为弧度：
$$
\theta = \frac{30}{180} \pi = \frac{\pi}{6}
$$

代入后单位向量变为：
$$
\mathbf{v}_1 = \begin{bmatrix} \cos\left(\frac{\pi}{6}\right) \\ \sin\left(\frac{\pi}{6}\right) \end{bmatrix}
= \begin{bmatrix} \frac{\sqrt{3}}{2} \\ \frac{1}{2} \end{bmatrix}, \quad
\mathbf{v}_2 = \begin{bmatrix} -\frac{1}{2} \\ \frac{\sqrt{3}}{2} \end{bmatrix}
$$

然后进行点积、缩放、拼接，得到两个投影向量，其和正好等于原始向量 $\mathbf{a}$，即完成一次**二维向量在任意正交基下的分解**。

---

这段代码在数学上等价于对 $\mathbb{R}^2$ 中任意向量做一次基变换和投影运算，是线性代数中“正交投影”与“坐标变换”的经典操作。

## 初始化

In [3]:
import numpy as np

## 定义向量 a

In [5]:
a = np.array([3,4])

## 自定函数

In [7]:
def decompose(a, theta):
    v1 = np.array([np.cos(theta), np.sin(theta)])
    v2 = np.array([-np.sin(theta), np.cos(theta)])

    # 标量投影 (坐标)
    a_v1 = np.dot(a,v1)
    a_v2 = np.dot(a,v2)

    # 向量投影 (正交分解)
    proj_a_v1 = a_v1 * v1
    proj_a_v2 = a_v2 * v2

    return proj_a_v1,proj_a_v2

## 正交分解

In [9]:
theta = 30
theta = theta /180 * np.pi

In [10]:
proj_a_v1,proj_a_v2 = decompose(a, theta)

In [11]:
proj_a_v1

array([3.98205081, 2.29903811])

In [12]:
proj_a_v2

array([-0.98205081,  1.70096189])

## 验证

In [14]:
proj_a_v1 + proj_a_v2

array([3., 4.])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  