Chapter 03

# 矩阵乘法第三视角
《线性代数》 | 鸢尾花书：数学不难

这段代码的核心任务是执行矩阵运算，特别是矩阵转置和矩阵乘法。我们详细分析各个步骤的数学意义，并给出相应的公式。

### **1. 初始化与矩阵定义**
代码首先使用 `numpy` 定义了一个 $2 \times 3$ 矩阵 $A$：
$$
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
$$
然后计算其转置 $B$：
$$
B = A^T = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}
$$

### **2. 计算矩阵 $C = A B$**
矩阵 $C$ 的计算过程如下：
$$
C = A B = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
\begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}
$$

逐列计算 $C$ 的每一列：
- 第一列：
  $$
  c_1 = A \cdot B_{[:,1]} = A \cdot \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}
 $$
  计算得：
  $$
  c_1 = \begin{bmatrix} 1 \cdot 1 + 2 \cdot 2 + 3 \cdot 3 \\ 4 \cdot 1 + 5 \cdot 2 + 6 \cdot 3 \end{bmatrix}
  = \begin{bmatrix} 14 \\ 32 \end{bmatrix}
 $$

- 第二列：
  $$
  c_2 = A \cdot B_{[:,2]} = A \cdot \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}
 $$
  计算得：
  $$
  c_2 = \begin{bmatrix} 1 \cdot 4 + 2 \cdot 5 + 3 \cdot 6 \\ 4 \cdot 4 + 5 \cdot 5 + 6 \cdot 6 \end{bmatrix}
  = \begin{bmatrix} 32 \\ 77 \end{bmatrix}
 $$

拼接 $c_1$ 和 $c_2$，得到完整的矩阵 $C$：
$$
C = \begin{bmatrix} 14 & 32 \\ 32 & 77 \end{bmatrix}
$$

### **3. 计算矩阵 $D = B A$**
类似地，计算 $D = B A$：
$$
D = B A = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}
\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
$$

逐列计算 $D$ 的每一列：
- 第一列：
  $$
  d_1 = B \cdot A_{[:,1]} = B \cdot \begin{bmatrix} 1 \\ 4 \end{bmatrix}
 $$
  计算得：
  $$
  d_1 = \begin{bmatrix} 1 \cdot 1 + 4 \cdot 4 \\ 2 \cdot 1 + 5 \cdot 4 \\ 3 \cdot 1 + 6 \cdot 4 \end{bmatrix}
  = \begin{bmatrix} 17 \\ 22 \\ 27 \end{bmatrix}
 $$

- 第二列：
  $$
  d_2 = B \cdot A_{[:,2]} = B \cdot \begin{bmatrix} 2 \\ 5 \end{bmatrix}
 $$
  计算得：
  $$
  d_2 = \begin{bmatrix} 1 \cdot 2 + 4 \cdot 5 \\ 2 \cdot 2 + 5 \cdot 5 \\ 3 \cdot 2 + 6 \cdot 5 \end{bmatrix}
  = \begin{bmatrix} 22 \\ 29 \\ 36 \end{bmatrix}
 $$

- 第三列：
  $$
  d_3 = B \cdot A_{[:,3]} = B \cdot \begin{bmatrix} 3 \\ 6 \end{bmatrix}
 $$
  计算得：
  $$
  d_3 = \begin{bmatrix} 1 \cdot 3 + 4 \cdot 6 \\ 2 \cdot 3 + 5 \cdot 6 \\ 3 \cdot 3 + 6 \cdot 6 \end{bmatrix}
  = \begin{bmatrix} 27 \\ 36 \\ 45 \end{bmatrix}
 $$

拼接 $d_1, d_2, d_3$ 得：
$$
D = \begin{bmatrix} 17 & 22 & 27 \\ 22 & 29 & 36 \\ 27 & 36 & 45 \end{bmatrix}
$$

### **4. 结论**
- $C = A A^T$ 是 $2 \times 2$ 的对称矩阵，它表示矩阵 $A$ 的行向量之间的内积。
- $D = A^T A$ 是 $3 \times 3$ 的对称矩阵，它表示矩阵 $A$ 的列向量之间的内积。

这两个矩阵分别出现在许多数学领域，例如：
- $A A^T$ 出现在协方差矩阵计算中，用于衡量不同样本（行）之间的关系。
- $A^T A$ 出现在主成分分析（PCA）中，用于衡量不同特征（列）之间的关系。

整个代码实际上是构建 $A A^T$ 和 $A^T A$，并详细拆解了其计算过程。

## 初始化

In [5]:
import numpy as np

## 定义矩阵 A

In [7]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

## 计算矩阵 B，即 A 的转置

In [9]:
B = A.T

## 计算矩阵乘法 C = A @ B

In [11]:
C = A @ B
C

array([[14, 32],
       [32, 77]])

## 第一列 $c_1$

In [13]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
B[:,[0]]

array([[1],
       [2],
       [3]])

In [15]:
c_1 = A @ B[:,[0]]
c_1

array([[14],
       [32]])

## 第二列 $c_2$

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
B[:,[1]]

array([[4],
       [5],
       [6]])

In [19]:
c_2 = A @ B[:,[1]]
c_2

array([[32],
       [77]])

## 左右排列得到C

In [21]:
np.block([c_1, c_2])

array([[14, 32],
       [32, 77]])

## 计算B @ A

In [23]:
D = B @ A
D

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

## 第一列 $d_1$

In [25]:
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
A[:,[0]]

array([[1],
       [4]])

In [27]:
d_1 = B @ A[:,[0]]
d_1

array([[17],
       [22],
       [27]])

## 第一列 $d_2$

In [29]:
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
A[:,[1]]

array([[2],
       [5]])

In [31]:
d_2 = B @ A[:,[1]]
d_2

array([[22],
       [29],
       [36]])

## 第三列 $d_3$

In [33]:
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
A[:,[2]]

array([[3],
       [6]])

In [35]:
d_3 = B @ A[:,[2]]
d_3

array([[27],
       [36],
       [45]])

## 左右排列得到D

In [37]:
np.block([d_1, d_2, d_3])

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  