Chapter 09

# 施密特正交化
《线性代数》 | 鸢尾花书：数学不难

这段代码实现的是三维向量的 **格拉姆-施密特正交化（Gram-Schmidt Orthogonalization）**，目的是将矩阵 $A$ 的列向量 $\boldsymbol{a}_1, \boldsymbol{a}_2, \boldsymbol{a}_3$ 转换为一组单位正交基 $\boldsymbol{q}_1, \boldsymbol{q}_2, \boldsymbol{q}_3$，使得 $Q = [\boldsymbol{q}_1\ \boldsymbol{q}_2\ \boldsymbol{q}_3]$ 满足 $Q^\top Q = I$，即每个向量长度为1且两两正交。

---

### 初始化与列向量提取

首先定义一个矩阵  
$$
A = \begin{bmatrix}
2 & 2 & 0 \\
2 & 0 & 2 \\
0 & 2 & 2
\end{bmatrix}
$$  
随后提取其三列，分别命名为 $\boldsymbol{a}_1, \boldsymbol{a}_2, \boldsymbol{a}_3$，用于后续正交化处理。

---

### 第一步：构造 $\boldsymbol{q}_1$

$$
\boldsymbol{q}_1 = \frac{\boldsymbol{a}_1}{\|\boldsymbol{a}_1\|}
$$

这一步将 $\boldsymbol{a}_1$ 单位化，得到 $\boldsymbol{q}_1$。此时 $\boldsymbol{q}_1$ 是一个单位向量，方向与 $\boldsymbol{a}_1$ 相同。验证 $\boldsymbol{q}_1^\top \boldsymbol{q}_1 = 1$ 说明其已标准化。

---

### 第二步：构造 $\boldsymbol{q}_2$

将 $\boldsymbol{a}_2$ 在 $\boldsymbol{q}_1$ 方向上投影并减去：

$$
\boldsymbol{\eta}_2 = \boldsymbol{a}_2 - (\boldsymbol{q}_1 \boldsymbol{q}_1^\top)\boldsymbol{a}_2
$$

其中，$\boldsymbol{q}_1 \boldsymbol{q}_1^\top$ 是一个**投影矩阵**，将任意向量投影到 $\boldsymbol{q}_1$ 所张成的一维子空间上。

然后将残差向量单位化：

$$
\boldsymbol{q}_2 = \frac{\boldsymbol{\eta}_2}{\|\boldsymbol{\eta}_2\|}
$$

这样得到的 $\boldsymbol{q}_2$ 与 $\boldsymbol{q}_1$ 正交，且是单位向量。验证 $\boldsymbol{q}_2^\top \boldsymbol{q}_2 = 1$ 和 $\boldsymbol{q}_1^\top \boldsymbol{q}_2 = 0$，分别说明单位化和正交性成立。

---

### 第三步：构造 $\boldsymbol{q}_3$

从 $\boldsymbol{a}_3$ 中减去它在 $\boldsymbol{q}_1$ 和 $\boldsymbol{q}_2$ 上的投影：

$$
\boldsymbol{\eta}_3 = \boldsymbol{a}_3 - (\boldsymbol{q}_1 \boldsymbol{q}_1^\top)\boldsymbol{a}_3 - (\boldsymbol{q}_2 \boldsymbol{q}_2^\top)\boldsymbol{a}_3
$$

然后单位化：

$$
\boldsymbol{q}_3 = \frac{\boldsymbol{\eta}_3}{\|\boldsymbol{\eta}_3\|}
$$

此时 $\boldsymbol{q}_3$ 与前两个向量都正交且单位长度。验证 $\boldsymbol{q}_1^\top \boldsymbol{q}_3 = 0$，$\boldsymbol{q}_2^\top \boldsymbol{q}_3 = 0$ 即可确认三向量两两正交。

---

### 向量投影补充

代码中也单独计算了 $\boldsymbol{a}_3$ 在 $\boldsymbol{q}_1$ 与 $\boldsymbol{q}_2$ 上的投影：

- 在 $\boldsymbol{q}_1$ 上的投影为：
  $$
  \text{proj}_{\boldsymbol{q}_1}(\boldsymbol{a}_3) = \boldsymbol{q}_1 \boldsymbol{q}_1^\top \boldsymbol{a}_3
  $$

- 在 $\boldsymbol{q}_2$ 上的投影为：
  $$
  \text{proj}_{\boldsymbol{q}_2}(\boldsymbol{a}_3) = \boldsymbol{q}_2 \boldsymbol{q}_2^\top \boldsymbol{a}_3
  $$

合并起来，$\boldsymbol{a}_3$ 在子空间 $\text{span}(\boldsymbol{q}_1, \boldsymbol{q}_2)$ 上的投影是两者的和。

---

### 总结

最终通过格拉姆-施密特过程，将原始矩阵 $A$ 的三列向量正交化，得到三列单位正交向量 $[\boldsymbol{q}_1\ \boldsymbol{q}_2\ \boldsymbol{q}_3]$，它们组成一个正交矩阵 $Q$，满足：

$$
Q^\top Q = I,\quad Q Q^\top = I
$$

这组向量构成了 $\mathbb{R}^3$ 中的一个正交基，适合用于QR分解、正交投影、最小二乘等计算。

## 初始化

In [3]:
import numpy as np

## 创建数据

In [5]:
A = np.array([
    [2, 2, 0],
    [2, 0, 2],
    [0, 2, 2]])

In [6]:
a1 = A[:,[0]]
a2 = A[:,[1]]
a3 = A[:,[2]]

## 第一步

In [8]:
q1 = a1/np.linalg.norm(a1)
q1

array([[0.70710678],
       [0.70710678],
       [0.        ]])

In [9]:
# 验证，单位化
q1.T @ q1

array([[1.]])

## 第二步

In [11]:
np.eye(3) - q1 @ q1.T

array([[ 0.5, -0.5,  0. ],
       [-0.5,  0.5,  0. ],
       [ 0. ,  0. ,  1. ]])

In [12]:
eta_2 = a2 - q1 @ q1.T @ a2
eta_2

array([[ 1.],
       [-1.],
       [ 2.]])

In [13]:
q2 = eta_2/np.linalg.norm(eta_2)
q2

array([[ 0.40824829],
       [-0.40824829],
       [ 0.81649658]])

In [14]:
a2_proj_q1 = q1 @ q1.T @ a2
a2_proj_q1

array([[1.],
       [1.],
       [0.]])

In [15]:
# 验证，单位化
q2.T @ q2

array([[1.]])

In [16]:
I = np.eye(3)
I - q1 @ q1.T- q2 @ q2.T

array([[ 0.33333333, -0.33333333, -0.33333333],
       [-0.33333333,  0.33333333,  0.33333333],
       [-0.33333333,  0.33333333,  0.33333333]])

In [17]:
# 验证，正交，
q1.T @ q2

array([[1.11022302e-16]])

## 第三步

In [19]:
eta_3 = a3 - q1 @ q1.T @ a3 - q2 @ q2.T @ a3

In [20]:
eta_3

array([[-1.33333333],
       [ 1.33333333],
       [ 1.33333333]])

In [21]:
q3 = eta_3/np.linalg.norm(eta_3)
q3

array([[-0.57735027],
       [ 0.57735027],
       [ 0.57735027]])

In [22]:
# 验证，正交，
q1.T @ q3

array([[0.]])

In [23]:
# 验证，正交，
q2.T @ q3

array([[-1.66533454e-16]])

In [24]:
a3_proj_q1_q2 = q1 @ q1.T @ a3 + q2 @ q2.T @ a3

In [25]:
a3_proj_q1 = q1 @ q1.T @ a3
a3_proj_q1

array([[1.],
       [1.],
       [0.]])

In [26]:
a3_proj_q2 = q2 @ q2.T @ a3
a3_proj_q2

array([[ 0.33333333],
       [-0.33333333],
       [ 0.66666667]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  