Chapter 02

# 计算矩阵乘法的每个元素
《线性代数》 | 鸢尾花书：数学不难

这段代码主要演示了如何使用 Python 和 NumPy 进行矩阵运算，特别是矩阵乘法的计算和分块验证。具体来说，代码定义了两个矩阵 $A$ 和 $B$，其中 $A$ 是一个 $2 \times 3$ 的矩阵，$B$ 是一个 $3 \times 2$ 的矩阵，形式如下：

$$
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}, \quad
B = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}
$$

代码首先计算了矩阵 $A$ 和 $B$ 的乘积 $C = A @ B$，即：

$$
C = A \cdot B = \begin{bmatrix} 1 \cdot 1 + 2 \cdot 2 + 3 \cdot 3 & 1 \cdot 4 + 2 \cdot 5 + 3 \cdot 6 \\ 4 \cdot 1 + 5 \cdot 2 + 6 \cdot 3 & 4 \cdot 4 + 5 \cdot 5 + 6 \cdot 6 \end{bmatrix} = \begin{bmatrix} 14 & 32 \\ 32 & 77 \end{bmatrix}
$$

接下来，代码通过提取矩阵 $A$ 的行和矩阵 $B$ 的列，验证了矩阵乘法的分块计算。具体来说：

1. 提取矩阵 $A$ 的第一行 $a_1$ 和第二行 $a_2$：
   $$
   a_1 = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}, \quad
   a_2 = \begin{bmatrix} 4 & 5 & 6 \end{bmatrix}
   $$

2. 提取矩阵 $B$ 的第一列 $b_1$ 和第二列 $b_2$：
   $$
   b_1 = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, \quad
   b_2 = \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}
   $$

3. 计算 $a_1$ 和 $b_1$ 的乘积：
   $$
   a_1 \cdot b_1 = 1 \cdot 1 + 2 \cdot 2 + 3 \cdot 3 = 14
   $$

4. 计算 $a_1$ 和 $b_2$ 的乘积：
   $$
   a_1 \cdot b_2 = 1 \cdot 4 + 2 \cdot 5 + 3 \cdot 6 = 32
   $$

5. 计算 $a_2$ 和 $b_1$ 的乘积：
   $$
   a_2 \cdot b_1 = 4 \cdot 1 + 5 \cdot 2 + 6 \cdot 3 = 32
   $$

6. 计算 $a_2$ 和 $b_2$ 的乘积：
   $$
   a_2 \cdot b_2 = 4 \cdot 4 + 5 \cdot 5 + 6 \cdot 6 = 77
   $$

通过这些计算，代码验证了矩阵乘法的分块性质，即矩阵乘积 $C$ 的每个元素 $C_{ij}$ 可以通过 $A$ 的第 $i$ 行与 $B$ 的第 $j$ 列的点积得到。

最后，代码计算了矩阵 $B$ 和 $A$ 的乘积 $D = B @ A$，即：

$$
D = B \cdot A = \begin{bmatrix} 1 \cdot 1 + 4 \cdot 4 & 1 \cdot 2 + 4 \cdot 5 & 1 \cdot 3 + 4 \cdot 6 \\ 2 \cdot 1 + 5 \cdot 4 & 2 \cdot 2 + 5 \cdot 5 & 2 \cdot 3 + 5 \cdot 6 \\ 3 \cdot 1 + 6 \cdot 4 & 3 \cdot 2 + 6 \cdot 5 & 3 \cdot 3 + 6 \cdot 6 \end{bmatrix} = \begin{bmatrix} 17 & 22 & 27 \\ 22 & 29 & 36 \\ 27 & 36 & 45 \end{bmatrix}
$$

这段代码通过具体的数值计算，展示了矩阵乘法的定义、分块计算以及矩阵乘法的不可交换性（即 $A \cdot B \neq B \cdot A$）。

## 初始化

In [4]:
import numpy as np  # 导入 NumPy 库，用于矩阵运算

## 定义矩阵 A

In [6]:
A = np.array([[1, 2, 3],  # 创建一个 2x3 的矩阵 A
              [4, 5, 6]])  # 矩阵 A 的第二行

## 定义矩阵 B

In [8]:
B = np.array([[1, 4],  # 创建一个 3x2 的矩阵 B
              [2, 5],  # 矩阵 B 的第二行
              [3, 6]])  # 矩阵 B 的第三行

## 计算矩阵 A 和 B 的乘积

In [10]:
C = A @ B  # 使用 @ 运算符计算矩阵 A 和 B 的乘积
C # 打印矩阵乘积

array([[14, 32],
       [32, 77]])

## 提取矩阵 A 的第一行

In [12]:
a_1 = A[[0], :]  # 提取矩阵 A 的第一行，结果为 1x3 矩阵
a_1  # 打印 a_1

array([[1, 2, 3]])

## 提取矩阵 A 的第二行

In [14]:
a_2 = A[[1], :]  # 提取矩阵 A 的第二行，结果为 1x3 矩阵
a_2  # 打印 a_2

array([[4, 5, 6]])

## 提取矩阵 B 的第一列

In [16]:
b1 = B[:, [0]]  # 提取矩阵 B 的第一列，结果为 3x1 矩阵
b1  # 打印 b1

array([[1],
       [2],
       [3]])

## 提取矩阵 B 的第二列

In [18]:
b2 = B[:, [1]]  # 提取矩阵 B 的第二列，结果为 3x1 矩阵
b2  # 打印 b2

array([[4],
       [5],
       [6]])

## 计算 a_1 和 b1 的乘积

In [20]:
a_1 @ b1  # 计算 a_1 和 b1 的矩阵乘积，结果为 1x1 矩阵

array([[14]])

## 计算 a_1 和 b2 的乘积

In [22]:
a_1 @ b2  # 计算 a_1 和 b2 的矩阵乘积，结果为 1x1 矩阵

array([[32]])

## 计算 a_2 和 b1 的乘积

In [24]:
a_2 @ b1  # 计算 a_2 和 b1 的矩阵乘积，结果为 1x1 矩阵

array([[32]])

## 计算 a_2 和 b2 的乘积

In [26]:
a_2 @ b2  # 计算 a_2 和 b2 的矩阵乘积，结果为 1x1 矩阵

array([[77]])

## 计算矩阵 B 和 A 的乘积

In [28]:
B @ A  # 使用 @ 运算符计算矩阵 B 和 A 的乘积

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  