Chapter 03

# 矩阵乘法第一视角
《线性代数》 | 鸢尾花书：数学不难

这段代码主要涉及矩阵的基本运算，包括矩阵转置、矩阵乘法，以及通过循环逐元素计算矩阵乘积的方式。以下是详细的数学解析：

### 1. 定义矩阵 $A$

代码首先定义了一个 $2 \times 3$ 矩阵 $A$：
$$
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
$$
其中，$A$ 具有 2 行 3 列。

### 2. 计算 $A$ 的转置矩阵 $B$

转置操作将矩阵的行和列进行交换，即：
$$
B = A^T = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}
$$
$B$ 是 $3 \times 2$ 矩阵。

### 3. 计算矩阵乘积 $C = A \times B$

矩阵 $C$ 由 $A$ 和 $B$ 进行矩阵乘法得到：
$$
C = A B
$$
根据矩阵乘法的定义，若 $A$ 为 $m \times n$ 矩阵，$B$ 为 $n \times p$ 矩阵，则矩阵乘法的结果是 $m \times p$ 维矩阵，其元素计算公式如下：
$$
C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}
$$
具体计算：
$$
C = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
    \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}
$$

计算各个元素：
$$
C_{11} = 1 \times 1 + 2 \times 2 + 3 \times 3 = 14
$$
$$
C_{12} = 1 \times 4 + 2 \times 5 + 3 \times 6 = 32
$$
$$
C_{21} = 4 \times 1 + 5 \times 2 + 6 \times 3 = 32
$$
$$
C_{22} = 4 \times 4 + 5 \times 5 + 6 \times 6 = 77
$$

最终得到：
$$
C = \begin{bmatrix} 14 & 32 \\ 32 & 77 \end{bmatrix}
$$

### 4. 计算 $C$ 的特定元素

代码提取 $A$ 的第一行：
$$
A_{1,:} = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}
$$
提取 $B$ 的第一列：
$$
B_{:,1} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}
$$
计算：
$$
A_{1,:} B_{:,1} = 1 \times 1 + 2 \times 2 + 3 \times 3 = 14
$$

### 5. 逐元素计算 $C$

代码通过两层循环遍历矩阵 $C$ 的每个元素，并使用矩阵乘法计算 $C_{ij}$：
$$
C_{ij} = A[i,:] \times B[:,j]
$$
这一过程等价于矩阵乘法的定义，验证了 $C$ 的计算正确性。

### 6. 计算 $D = B \times A$

接下来，代码计算 $B$ 和 $A$ 的矩阵乘法：
$$
D = B A
$$

$$
D = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}
    \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
$$

计算每个元素：
$$
D_{11} = 1 \times 1 + 4 \times 4 = 17, \quad
D_{12} = 1 \times 2 + 4 \times 5 = 22, \quad
D_{13} = 1 \times 3 + 4 \times 6 = 27
$$
$$
D_{21} = 2 \times 1 + 5 \times 4 = 22, \quad
D_{22} = 2 \times 2 + 5 \times 5 = 29, \quad
D_{23} = 2 \times 3 + 5 \times 6 = 36
$$
$$
D_{31} = 3 \times 1 + 6 \times 4 = 27, \quad
D_{32} = 3 \times 2 + 6 \times 5 = 36, \quad
D_{33} = 3 \times 3 + 6 \times 6 = 45
$$

最终：
$$
D = \begin{bmatrix} 17 & 22 & 27 \\ 22 & 29 & 36 \\ 27 & 36 & 45 \end{bmatrix}
$$

### 7. 计算 $D$ 的特定元素

代码提取 $B$ 的第一行：
$$
B_{1,:} = \begin{bmatrix} 1 & 4 \end{bmatrix}
$$
提取 $A$ 的第一列：
$$
A_{:,1} = \begin{bmatrix} 1 \\ 4 \end{bmatrix}
$$
计算：
$$
B_{1,:} A_{:,1} = 1 \times 1 + 4 \times 4 = 17
$$

### 8. 逐元素计算 $D$

同理，通过两层循环遍历 $D$ 的每个元素：
$$
D_{ij} = B[i,:] \times A[:,j]
$$
这再次验证了 $D$ 的正确性。

### 总结

- 代码展示了矩阵转置、矩阵乘法，以及如何手动计算矩阵乘法的每个元素。
- 通过遍历计算 $C$ 和 $D$，代码验证了 NumPy 矩阵乘法的正确性。
- 计算 $C$ 和 $D$ 的特定元素展示了矩阵乘法的计算原理。
- 数学上，$A B$ 和 $B A$ 由于矩阵维度不同，结果维度和数值均不同，即：
  $$
  A B \neq B A
  $$
  这表明矩阵乘法不是交换的（即 $A B \neq B A$ 一般不成立）。

## 初始化

In [3]:
import numpy as np

## 定义矩阵 A

In [5]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

## 计算矩阵 B，即 A 的转置

In [7]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

## 计算矩阵乘法 A @ B

In [9]:
C = A @ B
C

array([[14, 32],
       [32, 77]])

## 计算 C 的第1行、第1列

In [11]:
A[[0],:]

array([[1, 2, 3]])

In [12]:
B[:,[0]]

array([[1],
       [2],
       [3]])

In [13]:
A[[0],:] @ B[:,[0]]

array([[14]])

## 逐元素计算 C 的每个元素

In [15]:
rows, cols = C.shape
C_manual = np.zeros((rows, cols))  # 创建一个相同形状的零矩阵

In [16]:
for i in range(rows):
    for j in range(cols):
        c_ij = A[[i],:] @ B[:,[j]]
        c_ij = c_ij[0][0]
        C_manual[i, j] = c_ij

In [17]:
C_manual

array([[14., 32.],
       [32., 77.]])

## 计算 B @ A

In [19]:
D = B @ A
D

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

## 计算 D 的第1行、第1列

In [21]:
B[[0],:]

array([[1, 4]])

In [22]:
A[:,[0]]

array([[1],
       [4]])

In [23]:
B[[0],:] @ A[:,[0]]

array([[17]])

## 逐元素计算 D 的每个元素

In [25]:
rows, cols = D.shape
D_manual = np.zeros((rows, cols))  # 创建一个相同形状的零矩阵

In [26]:
for i in range(rows):
    for j in range(cols):
        d_ij = B[[i],:] @ A[:,[j]]
        d_ij = d_ij[0][0]
        D_manual[i, j] = d_ij

In [27]:
D_manual

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  