Chapter 03

# Python自定义函数计算矩阵乘法，内积视角
《线性代数》 | 鸢尾花书：数学不难

这段代码实现的是**矩阵乘法**的几何解释与程序实现，特别强调了**第一视角**（即逐元素构造的视角），并通过 Python 中 `numpy` 模块中的数组操作来实现矩阵乘法的底层过程。下面从**数学角度**对这段代码进行详细解析，包含必要的数学公式，并解释各个步骤在数学中代表的含义。

---

### **1. 矩阵乘法的数学基础**

设有两个矩阵 $A \in \mathbb{R}^{m \times p}$ 和 $B \in \mathbb{R}^{p \times n}$，那么它们的乘积 $C = AB$ 是一个 $m \times n$ 的矩阵，其中第 $i$ 行第 $j$ 列元素 $C_{ij}$ 的计算方式是：

$$
C_{ij} = \sum_{k=1}^{p} A_{ik} B_{kj}
$$

这就是矩阵乘法的核心定义。

等价地，我们也可以将每个元素看作是：
$$
C_{ij} = \text{dot}(A_{i,:}, B_{:,j})
$$

其中：
- $A_{i,:}$ 是矩阵 $A$ 的第 $i$ 行（行向量）
- $B_{:,j}$ 是矩阵 $B$ 的第 $j$ 列（列向量）

它们的点积等价于上面的求和公式。

---

### **2. 代码功能解释**

函数 `matrix_multiplication(A, B)` 实现了上述的数学过程：

- 首先，它检查矩阵 $A$ 的列数是否等于矩阵 $B$ 的行数，即 $p_A = p_B$，这是矩阵乘法的基本条件。
- 然后，它初始化一个零矩阵 $C \in \mathbb{R}^{m \times n}$，用于存储结果。
- 最后，通过两层循环，对每一个位置 $(i,j)$，取出 $A$ 的第 $i$ 行向量 $A_{i,:}$ 和 $B$ 的第 $j$ 列向量 $B_{:,j}$，并用 `np.dot()` 计算内积，即 $C_{ij}$。

这种写法提供了“第一视角”的直观性：你可以看作每个元素 $C_{ij}$ 是通过对应的一行一列计算得来的，而不是整块矩阵乘起来的黑箱操作。

---

### **3. 示例分析**

定义矩阵：
$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix} \in \mathbb{R}^{2 \times 3}
$$

其转置为：
$$
B = A^T = \begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix} \in \mathbb{R}^{3 \times 2}
$$

#### **计算 $AB$：**

$A \in \mathbb{R}^{2 \times 3}$，$B \in \mathbb{R}^{3 \times 2}$，所以乘积 $C = AB \in \mathbb{R}^{2 \times 2}$，每个元素计算如下：

- $C_{11} = 1 \cdot 1 + 2 \cdot 2 + 3 \cdot 3 = 1 + 4 + 9 = 14$
- $C_{12} = 1 \cdot 4 + 2 \cdot 5 + 3 \cdot 6 = 4 + 10 + 18 = 32$
- $C_{21} = 4 \cdot 1 + 5 \cdot 2 + 6 \cdot 3 = 4 + 10 + 18 = 32$
- $C_{22} = 4 \cdot 4 + 5 \cdot 5 + 6 \cdot 6 = 16 + 25 + 36 = 77$

结果为：
$$
AB = \begin{bmatrix}
14 & 32 \\
32 & 77
\end{bmatrix}
$$

#### **计算 $BA$：**

$B \in \mathbb{R}^{3 \times 2}$，$A \in \mathbb{R}^{2 \times 3}$，所以乘积 $BA \in \mathbb{R}^{3 \times 3}$，每个元素也是按内积逐一计算。

比如第一个元素：
- $C_{11} = 1 \cdot 1 + 4 \cdot 4 = 1 + 16 = 17$

以此类推，可以手动验证其他元素，最终结果为：
$$
BA = \begin{bmatrix}
17 & 22 & 27 \\
22 & 29 & 36 \\
27 & 36 & 45
\end{bmatrix}
$$

---

### **4. 总结**

此函数从**线性代数中矩阵乘法的定义出发**，以编程方式逐一实现每个元素的计算。通过使用行向量和列向量的内积，本质上是在做**向量空间中的投影**操作，每个结果元素 $C_{ij}$ 都是 $A$ 的第 $i$ 行与 $B$ 的第 $j$ 列在 $p$ 维空间中的“相似度”或“相关性”。

该函数虽然不如 NumPy 的 `np.matmul` 或 `@` 运算符高效，但在教学和理解上是极其直观和有价值的。

## 初始化

In [4]:
import numpy as np

## 自定义函数，矩阵乘法第一视角

In [6]:
def matrix_multiplication_inner(A, B):
    
    # 获取矩阵 A 和 B 的形状
    m, p_A = A.shape
    p_B, n = B.shape

    # 检测矩阵形状是否符合矩阵乘法规则
    if p_A != p_B:
        raise ValueError('Dimensions do not match')

    # 初始化结果矩阵 C，形状 (m, n)，初始值设为 0
    C = np.zeros((m, n))

    # 计算每个元素
    for i in range(m):
        for j in range(n):
            row_i_A = A[i, :]        # A 的第 i 行（行向量）
            col_j_B = B[:, j]        # B 的第 j 列（列向量）
            C[i, j] = np.dot(row_i_A, col_j_B)  # 计算内积

    return C

## 矩阵乘法

In [8]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

## 矩阵乘法

In [11]:
matrix_multiplication_inner(A, B)

array([[14., 32.],
       [32., 77.]])

In [12]:
matrix_multiplication_inner(B, A)

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  