Chapter 06

# 基底转换
《线性代数》 | 鸢尾花书：数学不难

这段代码的核心任务是研究**向量在线性变换下的坐标变换**，并将其在两个不同基底中进行表示：一个是**标准正交基**，另一个是一个**非标准但正交的基底 $V$**。整个过程结合了**线性变换**、**基变换**与**向量坐标表示**等概念，下面我们从数学视角详细解读各步骤。

---

首先，定义了一个线性变换矩阵：

$$
A = \begin{bmatrix}
-1 & 0 \\
0 & -1
\end{bmatrix}
$$

这个矩阵是一个**中心对称变换（central inversion）**，它将任意二维向量 $\mathbf{v} \in \mathbb{R}^2$ 映射到其相反向量 $-\mathbf{v}$，也就是关于原点的对称。该变换具有如下性质：

- 是正交矩阵：$A^\top A = I$
- 行列式为正：$\det(A) = 1$
- 自伴算子：$A = A^\top$

接下来定义一个向量 $\mathbf{a}$，其在基底 $A$ 所对应的坐标为：

$$
\mathbf{x}_A = \begin{bmatrix} -3 \\ -4 \end{bmatrix}
$$

这里的“在 $A$ 中的坐标”其实指的是 $\mathbf{a}$ 在标准正交基下的坐标值，尚未变基。我们接下来用 $A \cdot \mathbf{x}_A$ 得到该向量在**标准正交基**下被 $A$ 作用后的结果：

$$
A \mathbf{x}_A = \begin{bmatrix} -1 & 0 \\ 0 & -1 \end{bmatrix} \begin{bmatrix} -3 \\ -4 \end{bmatrix} = \begin{bmatrix} 3 \\ 4 \end{bmatrix}
$$

也就是说，$\mathbf{x}_A$ 表示的是原始向量 $\mathbf{a}$，而 $A \mathbf{x}_A$ 是它变换后的向量（即被 $A$ 作用之后的向量）。

---

接下来引入了一个新的正交基底 $V$，定义为：

$$
V = \begin{bmatrix}
\frac{3}{5} & -\frac{4}{5} \\
\frac{4}{5} & \frac{3}{5}
\end{bmatrix}
$$

这个矩阵满足 $V^\top V = I$，即它是一个**正交矩阵**，可以看作是将标准基 $\{\mathbf{e}_1, \mathbf{e}_2\}$ 旋转一定角度得到的一组新基底 $\{\mathbf{v}_1, \mathbf{v}_2\}$，并且这组基底保持正交与单位长度。

由于 $V$ 是正交矩阵，其逆矩阵 $V^{-1}$ 等于其转置矩阵：

$$
V^{-1} = V^\top = \begin{bmatrix}
\frac{3}{5} & \frac{4}{5} \\
-\frac{4}{5} & \frac{3}{5}
\end{bmatrix}
$$

---

最后，计算 $\mathbf{a}$ 在新的基底 $V$ 中的坐标。为了得到这个坐标，先应用线性变换 $A$，再将结果从标准基转换为 $V$ 基。变换过程如下：

1. 计算变换后向量：$\mathbf{a}' = A \cdot \mathbf{x}_A$
2. 将其投影到新基底 $V$ 中：$\mathbf{x}_V = V^{-1} \cdot \mathbf{a}'$

综上，计算过程为：

$$
\mathbf{x}_V = V^{-1} A \mathbf{x}_A
$$

代入具体数值进行计算：

$$
\mathbf{x}_V = \begin{bmatrix}
\frac{3}{5} & \frac{4}{5} \\
-\frac{4}{5} & \frac{3}{5}
\end{bmatrix}
\begin{bmatrix}
-1 & 0 \\
0 & -1
\end{bmatrix}
\begin{bmatrix}
-3 \\
-4
\end{bmatrix}
= \begin{bmatrix}
\frac{3}{5} & \frac{4}{5} \\
-\frac{4}{5} & \frac{3}{5}
\end{bmatrix}
\begin{bmatrix}
3 \\
4
\end{bmatrix}
= \begin{bmatrix}
\frac{25}{5} \\
0
\end{bmatrix}
= \begin{bmatrix}
5 \\
0
\end{bmatrix}
$$

这意味着，在新的基底 $V$ 中，向量 $\mathbf{a}$（在 $A$ 作用后）只包含第一个基向量方向的分量，完全落在 $\mathbf{v}_1$ 的方向上。

---

从几何意义上，这段代码演示了一个经典的线性代数操作流程：

1. 给定一个线性变换 $A$；
2. 给定一个向量 $\mathbf{a}$；
3. 在标准正交基下施加 $A$；
4. 切换到一个新的正交基底 $V$；
5. 计算向量在该新基底下的表示。

它把抽象的矩阵乘法具体化为“坐标变化 + 基变换”的组合，体现了线性代数中坐标、基底、线性变换之间的深刻联系。

## 初始化

In [2]:
import numpy as np

## 定义基底 A

In [4]:
A = np.array([[-1, 0],
             [0, -1]])

## 向量 a 在 A 中坐标

In [6]:
x_A = np.array([[-3],
                [-4]])

In [7]:
A @ x_A
# 在标准正交基坐标

array([[3],
       [4]])

## 定义基底 V

In [9]:
V = np.array([[3/5, -4/5],
              [4/5, 3/5]])

In [10]:
V_inv = np.linalg.inv(V)
V_inv

array([[ 0.6,  0.8],
       [-0.8,  0.6]])

## 计算向量 a 在 V 中坐标

In [15]:
x_V = V_inv @ A @ x_A
x_V

array([[ 5.0000000e+00],
       [-8.8817842e-16]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  