Chapter 05

# NumPy计算逆矩阵
《线性代数》 | 鸢尾花书：数学不难

这段代码的目标是计算一个 \(2 \times 2\) 矩阵 \( K \) 的逆矩阵 \( K^{-1} \)。在数学上，给定一个可逆矩阵 \( K \)，它的逆矩阵满足：

$$
K K^{-1} = K^{-1} K = I
$$

其中 \( I \) 是单位矩阵：

$$
I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
$$

### 1. 定义矩阵 \( K \)
代码首先定义了矩阵 \( K \)：
$$
K = \begin{bmatrix} 1 & 0.5 \\ 0 & 1 \end{bmatrix}
$$
这里使用 `numpy` 的 `np.array()` 来创建矩阵，这种方式能够用于高效的数值计算。

### 2. 计算矩阵的逆
代码使用 `np.linalg.inv(K)` 计算矩阵 \( K \) 的逆矩阵。这是 `numpy` 提供的标准方法，适用于任何可逆矩阵。如果矩阵不可逆（即行列式为零），`numpy` 会抛出错误。

### 3. 计算逆矩阵
矩阵 \( K \) 的逆矩阵可以按照标准公式计算。对于 \( 2 \times 2 \) 矩阵：
$$
K = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
$$
如果矩阵可逆，它的逆矩阵公式为：
$$
K^{-1} = \frac{1}{\det(K)} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$
其中行列式：
$$
\det(K) = ad - bc
$$

对于当前矩阵：
$$
K = \begin{bmatrix} 1 & 0.5 \\ 0 & 1 \end{bmatrix}
$$
行列式计算如下：
$$
\det(K) = (1 \times 1) - (0.5 \times 0) = 1
$$

因此，矩阵 \( K \) 是可逆的，其逆矩阵计算如下：
$$
K^{-1} = \frac{1}{1} \begin{bmatrix} 1 & -0.5 \\ 0 & 1 \end{bmatrix}
= \begin{bmatrix} 1 & -0.5 \\ 0 & 1 \end{bmatrix}
$$

### 4. 代码的数学意义
代码利用 `np.linalg.inv(K)` 计算矩阵 \( K \) 的逆，并返回：
$$
K^{-1} = \begin{bmatrix} 1 & -0.5 \\ 0 & 1 \end{bmatrix}
$$
这意味着如果我们将 \( K \) 乘以它的逆矩阵 \( K^{-1} \)，就会得到单位矩阵 \( I \)：
$$
K K^{-1} = \begin{bmatrix} 1 & 0.5 \\ 0 & 1 \end{bmatrix} 
\begin{bmatrix} 1 & -0.5 \\ 0 & 1 \end{bmatrix} 
= \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} = I
$$
这验证了矩阵逆的正确性。

### 5. 代码的作用
这段代码提供了一种简洁的方法来计算可逆矩阵的逆矩阵，并确保计算结果满足数学定义，即 \( K K^{-1} = I \)。如果矩阵不可逆，则 `numpy` 会抛出错误，使用户可以避免错误计算。

## 初始化

In [5]:
import numpy as np

## 定义矩阵

In [7]:
K = np.array([[1, 0.5],
              [0, 1]])

In [9]:
K_inv = np.linalg.inv(K)
K_inv

array([[ 1. , -0.5],
       [ 0. ,  1. ]])

## 检查

In [11]:
K @ K_inv

array([[1., 0.],
       [0., 1.]])

In [13]:
K_inv @ K

array([[1., 0.],
       [0., 1.]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  