Chapter 03

# 矩阵乘法第四视角
《线性代数》 | 鸢尾花书：数学不难

## 初始化

In [4]:
import numpy as np

## 定义矩阵 A

In [6]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

## 计算矩阵 B，即 A 的转置

In [8]:
B = A.T

## 计算矩阵乘法 C = A @ B

In [10]:
C = A @ B
C

array([[14, 32],
       [32, 77]])

## 第一行 $c^{(1)}$

In [12]:
A[[0],:]

array([[1, 2, 3]])

In [13]:
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
c_1_row = A[[0],:] @ B
c_1_row

array([[14, 32]])

## 第二行 $c^{(2)}$

In [16]:
A[[1],:]

array([[4, 5, 6]])

In [17]:
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
c_2_row = A[[1],:] @ B
c_2_row

array([[32, 77]])

## 上下排列得到C

In [20]:
np.block([[c_1_row], [c_2_row]])

array([[14, 32],
       [32, 77]])

## 计算B @ A

In [22]:
D = B @ A
D

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

## 第一行 $d^{(1)}$

In [24]:
B[[0],:]

array([[1, 4]])

In [25]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
d_1_row = B[[0],:] @ A
d_1_row

array([[17, 22, 27]])

## 第二行 $d^{(2)}$

In [28]:
B[[1],:]

array([[2, 5]])

In [29]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
d_2_row = B[[1],:] @ A
d_2_row

array([[22, 29, 36]])

## 第三行 $d^{(2)}$

In [32]:
B[[2],:]

array([[3, 6]])

In [33]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
d_3_row = B[[2],:] @ A
d_3_row

array([[27, 36, 45]])

## 上下排列得到D

In [36]:
np.block([[d_1_row], [d_2_row], [d_2_row]])

array([[17, 22, 27],
       [22, 29, 36],
       [22, 29, 36]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  