Chapter 03

# Python自定义函数计算矩阵乘法，外积视角
《线性代数》 | 鸢尾花书：数学不难

这段代码从**矩阵乘法的“第二视角”——列-行外积展开（Outer Product Expansion）**出发，对标准矩阵乘法进行了实现。在第一视角中，我们强调**每个元素是如何由行与列的点积计算得出**；而这里的“第二视角”强调的是：**整个矩阵乘积是多个秩1矩阵（外积）的线性叠加**。下面从数学角度详细解析，并穿插相应的公式表示。

---

### **1. 数学背景：外积展开视角的矩阵乘法**

给定两个矩阵：

- $A \in \mathbb{R}^{m \times p}$
- $B \in \mathbb{R}^{p \times n}$

设：
- $A$ 的列向量表示为 $A = \left[ \mathbf{a}^{(1)}, \mathbf{a}^{(2)}, \dots, \mathbf{a}^{(p)} \right]$, 其中 $\mathbf{a}^{(k)} \in \mathbb{R}^m$
- $B$ 的行向量表示为 $B = \begin{bmatrix} (\mathbf{b}^{(1)})^T \\ (\mathbf{b}^{(2)})^T \\ \vdots \\ (\mathbf{b}^{(p)})^T \end{bmatrix}$，其中 $\mathbf{b}^{(k)} \in \mathbb{R}^n$

那么，矩阵乘积 $C = AB$ 可以表示为**外积求和的形式**：

$$
C = AB = \sum_{k=1}^{p} \mathbf{a}^{(k)} (\mathbf{b}^{(k)})^T
$$

其中每一项 $\mathbf{a}^{(k)} (\mathbf{b}^{(k)})^T$ 是一个 $m \times n$ 的**秩1矩阵**（即行 rank 为1 的矩阵），代表了矩阵 $A$ 第 $k$ 列与矩阵 $B$ 第 $k$ 行之间的**外积**。

- $\mathbf{a}^{(k)}$ 是一个列向量 $\in \mathbb{R}^{m \times 1}$
- $(\mathbf{b}^{(k)})^T$ 是一个行向量 $\in \mathbb{R}^{1 \times n}$
- 它们的乘积 $\mathbf{a}^{(k)} (\mathbf{b}^{(k)})^T \in \mathbb{R}^{m \times n}$

这个视角强调了**矩阵乘积是一系列“结构简单”的秩1矩阵的叠加**，在神经网络、图像重构和张量分解中有广泛的应用。

---

### **2. 代码实现逻辑**

- 程序首先检查维度匹配，即确保 $A$ 的列数等于 $B$ 的行数。
- 初始化结果矩阵 $C$ 为零矩阵，维度为 $m \times n$。
- 对于每一个 $k = 0, 1, \dots, p-1$：
  - 从矩阵 $A$ 中提取第 $k$ 列向量 $a_k = A[:, [k]]$，形状为 $(m, 1)$
  - 从矩阵 $B$ 中提取第 $k$ 行向量 $b_k = B[[k], :]$，形状为 $(1, n)$
  - 计算外积：$a_k \cdot b_k$（用 `@` 运算符表示矩阵乘法）
  - 将该秩1矩阵加到 $C$ 中：$C \mathrel{+}= a_k \cdot b_k$

最终，$C$ 中累加了所有秩1矩阵之和，得到结果 $AB$。

---

### **3. 实例计算分析**

仍然考虑矩阵：

$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}, \quad B = A^T = \begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
$$

则乘积 $C = AB$ 是：

$$
AB = \sum_{k=1}^{3} \mathbf{a}^{(k)} (\mathbf{b}^{(k)})^T
$$

每一项如下（逐项展示）：

- 第1项（$k=1$）：
  $$
  \mathbf{a}^{(1)} = \begin{bmatrix} 1 \\ 4 \end{bmatrix}, \quad \mathbf{b}^{(1)} = \begin{bmatrix} 1 & 4 \end{bmatrix} \Rightarrow
  \mathbf{a}^{(1)} (\mathbf{b}^{(1)})^T =
  \begin{bmatrix}
  1 \cdot 1 & 1 \cdot 4 \\
  4 \cdot 1 & 4 \cdot 4
  \end{bmatrix}
  =
  \begin{bmatrix}
  1 & 4 \\
  4 & 16
  \end{bmatrix}
  $$

- 第2项（$k=2$）：
  $$
  \mathbf{a}^{(2)} = \begin{bmatrix} 2 \\ 5 \end{bmatrix}, \quad \mathbf{b}^{(2)} = \begin{bmatrix} 2 & 5 \end{bmatrix} \Rightarrow
  \mathbf{a}^{(2)} (\mathbf{b}^{(2)})^T =
  \begin{bmatrix}
  4 & 10 \\
  10 & 25
  \end{bmatrix}
  $$

- 第3项（$k=3$）：
  $$
  \mathbf{a}^{(3)} = \begin{bmatrix} 3 \\ 6 \end{bmatrix}, \quad \mathbf{b}^{(3)} = \begin{bmatrix} 3 & 6 \end{bmatrix} \Rightarrow
  \mathbf{a}^{(3)} (\mathbf{b}^{(3)})^T =
  \begin{bmatrix}
  9 & 18 \\
  18 & 36
  \end{bmatrix}
  $$

求和得到最终结果：

$$
AB = \begin{bmatrix}
1 + 4 + 9 & 4 + 10 + 18 \\
4 + 10 + 18 & 16 + 25 + 36
\end{bmatrix}
= \begin{bmatrix}
14 & 32 \\
32 & 77
\end{bmatrix}
$$

这与标准矩阵乘法一致，但构造方式完全不同，强调结构性。

---

### **4. 总结**

这段代码展示了矩阵乘法的**外积展开法（Outer Product Expansion）**的数学实质：

- 如果说第一视角强调**元素的点积计算**（局部视角），
- 那么第二视角强调的是**矩阵整体是秩1矩阵的叠加**（全局视角）。

这种方法在许多应用中极具启发性，特别是在需要对矩阵进行**低秩近似（low-rank approximation）**、**奇异值分解（SVD）**、**神经网络权重分解**等操作时。它揭示了矩阵乘法中“结构的本质”：一个复杂的矩阵结果可以由多个简单的 rank-1 结构组合而成。

## 初始化

In [3]:
import numpy as np

## 自定义函数，矩阵乘法第二视角

In [5]:
def matrix_multiplication_outer(A, B):
    
    # 获取矩阵 A 和 B 的形状
    m, p_A = A.shape
    p_B, n = B.shape

    # 检测矩阵形状是否符合矩阵乘法规则
    if p_A != p_B:
        raise ValueError('Dimensions do not match')

    # 初始化结果矩阵 C，形状 (m, n)，初始值设为 0
    C = np.zeros((m, n))

    for k in range(p_A):
        a_k = A[:, [k]]      # A 的第 k 列，二维数组
        b_k = B[[k], :]      # B 的第 k 行，二维数组
        C += (a_k @ b_k)     # 每次计算外积并加到结果中

    return C

## 矩阵乘法

In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

## 矩阵乘法

In [10]:
matrix_multiplication_outer(A, B)

array([[14., 32.],
       [32., 77.]])

In [11]:
matrix_multiplication_outer(B, A)

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  