Chapter 03

# 矩阵乘法第二视角
《线性代数》 | 鸢尾花书：数学不难

这段代码主要涉及矩阵运算，包括矩阵转置、矩阵乘法，以及对矩阵乘法的逐元素计算。接下来，从数学角度详细描述代码的计算过程，并结合数学公式进行解析。

---

### **1. 定义矩阵**
首先，定义一个 $2 \times 3$ 的矩阵 $A$：
$$
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
$$
然后，计算 $A$ 的转置矩阵 $B = A^T$，得到：
$$
B = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}
$$

---

### **2. 计算矩阵乘法 $C = A B$**
矩阵 $C$ 由 $A$ 和 $B$ 相乘得到，即：
$$
C = A B = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix} \times \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}
$$
按照矩阵乘法的定义：
$$
C_{ij} = \sum_{k=1}^{3} A_{ik} B_{kj}
$$
计算每个元素：
$$
C_{11} = 1 \times 1 + 2 \times 2 + 3 \times 3 = 14, \quad C_{12} = 1 \times 4 + 2 \times 5 + 3 \times 6 = 32
$$
$$
C_{21} = 4 \times 1 + 5 \times 2 + 6 \times 3 = 32, \quad C_{22} = 4 \times 4 + 5 \times 5 + 6 \times 6 = 77
$$
最终得到：
$$
C = \begin{bmatrix} 14 & 32 \\ 32 & 77 \end{bmatrix}
$$

---

### **3. 按列计算 $C$**
代码中逐列计算 $C$，即：
$$
C_1 = A_{[:, 0]} B_{[0, :]} = \begin{bmatrix} 1 \\ 4 \end{bmatrix} \times \begin{bmatrix} 1 & 4 \end{bmatrix} = \begin{bmatrix} 1 & 4 \\ 4 & 16 \end{bmatrix}
$$
$$
C_2 = A_{[:, 1]} B_{[1, :]} = \begin{bmatrix} 2 \\ 5 \end{bmatrix} \times \begin{bmatrix} 2 & 5 \end{bmatrix} = \begin{bmatrix} 4 & 10 \\ 10 & 25 \end{bmatrix}
$$
$$
C_3 = A_{[:, 2]} B_{[2, :]} = \begin{bmatrix} 3 \\ 6 \end{bmatrix} \times \begin{bmatrix} 3 & 6 \end{bmatrix} = \begin{bmatrix} 9 & 18 \\ 18 & 36 \end{bmatrix}
$$
叠加得到：
$$
C_1 + C_2 + C_3 = C
$$

---

### **4. 逐元素计算 $C$**
代码使用一个循环计算 $C$：
$$
C_{\text{manual}} = \sum_{k=1}^{3} C_k
$$
这是对矩阵乘法的分解计算方法，验证了矩阵乘法的正确性。

---

### **5. 计算 $D = B A$**
接下来计算矩阵 $D$：
$$
D = B A = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix} \times \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
$$
同样按照矩阵乘法的定义：
$$
D_{ij} = \sum_{k=1}^{2} B_{ik} A_{kj}
$$
计算各元素：
$$
D_{11} = 1 \times 1 + 4 \times 4 = 17, \quad D_{12} = 1 \times 2 + 4 \times 5 = 22, \quad D_{13} = 1 \times 3 + 4 \times 6 = 27
$$
$$
D_{21} = 2 \times 1 + 5 \times 4 = 22, \quad D_{22} = 2 \times 2 + 5 \times 5 = 29, \quad D_{23} = 2 \times 3 + 5 \times 6 = 36
$$
$$
D_{31} = 3 \times 1 + 6 \times 4 = 27, \quad D_{32} = 3 \times 2 + 6 \times 5 = 36, \quad D_{33} = 3 \times 3 + 6 \times 6 = 45
$$
最终得到：
$$
D = \begin{bmatrix} 17 & 22 & 27 \\ 22 & 29 & 36 \\ 27 & 36 & 45 \end{bmatrix}
$$

---

### **6. 按列计算 $D$**
代码逐列计算 $D$：
$$
D_1 = B_{[:, 0]} A_{[0, :]} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \times \begin{bmatrix} 1 & 2 & 3 \end{bmatrix} = \begin{bmatrix} 1 & 2 & 3 \\ 2 & 4 & 6 \\ 3 & 6 & 9 \end{bmatrix}
$$
$$
D_2 = B_{[:, 1]} A_{[1, :]} = \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix} \times \begin{bmatrix} 4 & 5 & 6 \end{bmatrix} = \begin{bmatrix} 16 & 20 & 24 \\ 20 & 25 & 30 \\ 24 & 30 & 36 \end{bmatrix}
$$
$$
D_1 + D_2 = D
$$

---

### **7. 逐元素计算 $D$**
代码使用循环计算 $D$：
$$
D_{\text{manual}} = \sum_{k=1}^{2} D_k
$$
这个方法验证了矩阵乘法的正确性，并通过逐步相加的方式计算出最终的矩阵乘积。

---

### **总结**
这段代码的核心内容是：
1. 计算 $A$ 的转置 $B$，然后计算 $A B$ 和 $B A$。
2. 通过列向量的方式分解矩阵乘法，将矩阵乘法表示为多个外积的叠加。
3. 使用循环实现矩阵乘法的分解计算，进一步验证矩阵乘法的正确性。

这种方法有助于理解矩阵乘法的本质，即矩阵乘法可以看作多个列向量（或行向量）的外积之和。这种思路对于深入理解矩阵运算、优化计算、以及理解机器学习中的矩阵操作非常重要。

## 初始化

In [4]:
import numpy as np

## 定义矩阵 A

In [6]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

## 计算矩阵 B，即 A 的转置

In [8]:
B = A.T

## 计算矩阵乘法 C = A @ B

In [10]:
C = A @ B
C

array([[14, 32],
       [32, 77]])

## $C_1$

In [12]:
A[:,[0]]

array([[1],
       [4]])

In [13]:
B[[0],:]

array([[1, 4]])

In [14]:
C_1 = A[:,[0]] @ B[[0],:]
C_1

array([[ 1,  4],
       [ 4, 16]])

## $C_2$

In [16]:
A[:,[1]]

array([[2],
       [5]])

In [17]:
B[[1],:]

array([[2, 5]])

In [18]:
C_2 = A[:,[1]] @ B[[1],:]
C_2

array([[ 4, 10],
       [10, 25]])

## $C_3$

In [20]:
A[:,[2]]

array([[3],
       [6]])

In [21]:
B[[2],:]

array([[3, 6]])

In [22]:
C_3 = A[:,[2]] @ B[[2],:]
C_3

array([[ 9, 18],
       [18, 36]])

## 叠加

In [24]:
C_1 + C_2 + C_3

array([[14, 32],
       [32, 77]])

## 逐元素计算 C 的每个元素

In [26]:
rows, cols = A.shape
C_manual = np.zeros_like(C)

for k in range(cols):
    C_k = A[:,[k]] @ B [[k],:]
    C_manual = C_manual + C_k

C_manual

array([[14, 32],
       [32, 77]])

## 计算B @ A

In [28]:
D = B @ A
D

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

## $D_k$

In [30]:
D_1 = B[:,[0]] @ A[[0],:]
D_1

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [31]:
D_2 = B[:,[1]] @ A[[1],:]
D_2

array([[16, 20, 24],
       [20, 25, 30],
       [24, 30, 36]])

## 叠加

In [33]:
D_1 + D_2

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

## 逐元素计算 D 的每个元素

In [35]:
rows, cols = B.shape
D_manual = np.zeros_like(D)

for k in range(cols):
    D_k = B[:,[k]] @ A[[k],:]
    D_manual = D_manual + D_k

In [36]:
D_manual

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  